server:
  port: 80
spring:
  servlet:
    multipart:
      # 设置 上传文件的大小
      max-file-size: 50MB
      # 设置 整个请求的大小
      max-request-size: 55MB
  application:
    name: tos_miaosha
  datasource:
    url: jdbc:mysql://101.33.228.113:3306/miaosha?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tqyyds
    redis:
      host: 101.43.251.185
#      host: localhost
      #Redis服务器连接端口
      port: 6379
      #Redis服务器连接密码（默认为空）
      password: yty123456
#      password:
      #连接超时时间（毫秒）
      timeout: 30000
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池中的最大空闲连接
        max-idle: 100
        #连接池中的最小空闲连接
        min-idle: 50
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://localhost:${server.port}
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
rocketmq:
  producer:
    group: demo_producer
    # 发送消息超时时间，默认是 3s
    send-message-timeout: 5000
    # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-failed: 2
    # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed: 2
    # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
    retry-next-server: false
  # 填你的IP
  name-server: 120.24.168.75:9876